version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env_docker
    depends_on:
      - mongo
    command: yarn start:prod

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  mongo_data:
