version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/house_numbers?authSource=admin
      - OPENAI_API_KEY=your_openai_api_key_here
    depends_on:
      - mongo
    command: yarn start:prod

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  mongo_data:
