import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            src="/logo-house-numbers.avif"
            alt="Next.js logo"
            width={236}
            height={72}
            priority
          />
          <ol>
            <li>
              <Link href="/create_snippets">Create a new snippet.</Link>
            </li>
            <li>
              <Link href="/snippet">Query a snippet by ID.</Link>
            </li>
          </ol>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://www.linkedin.com/in/juniorfurini/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/junior-furini.jpg"
              alt="File icon"
              width={32}
              height={32}
            />
            Junior Furini
          </a>
          <a
            href="https://github.com/jrfurini/hn_test_2025"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Github&apos;s repository
          </a>
        </footer>
      </div>
    </>
  );
}
